name: "Composer Lint"

on:
  pull_request:
    branches:
      - "master"
  push:

jobs:
  composer-lint:
    name: "Composer Lint"
    runs-on: "ubuntu-22.04"

    strategy:
      matrix:
        php-version:
          - 8.2

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2, composer-normalize:2
        env:
          COMPOSER_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Composer normalize"
        run: "composer-normalize --dry-run"
